### ISSUE TITLE
Organogram bug if you don't select primary profession

### ISSUE THREAD

**Issue by nmenezes0** [i-dot-ai/ellandi#209]
Select some professions. On the next page (`primary_profession`), if you don't select a primary profession and click continue, then you will get an error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/app/organogram/organogram/page_views.py", line 320, in page_view
    return view_map[page_name](request, url_data)
  File "/app/organogram/organogram/page_views.py", line 245, in primary_profession_view
    primary_profession = models.Profession.objects.get(pk=data["primary_profession"])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /primary_profession
Exception Value: Profession matching query does not exist.

```

**Comment by nmenezes0** [comment]
Closing as we're deleting organogram.
