### ISSUE TITLE
'/me' endpoint breaks after PATCH of 'Professions'

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#256]
Steps

1. Add to Professions e.g.
```lang-js
//PATCH:  /users/b242e91a-c07f-4137-9513-117f17c465f1/
{
... 
professions: ["Social Research", "Statistical Service", "Tax"]
}
```
2. `/me` endpoint starts to throw errors:

**Endpoint**: 
/me
Authorization: Token 5b0abd1188580ce4a25c5e08443ecd343941415ac3eba0e62c303fca96813fa9

![Screenshot 2022-08-01 at 11 39 25](https://user-images.githubusercontent.com/1698584/182130869-093e7663-7772-4e3d-93f0-36052737fd9d.png)

```
ellandi-api-1  | [01/Aug/2022 11:01:39] "OPTIONS /me HTTP/1.1" 200 0
ellandi-api-1  | Internal Server Error: /me
ellandi-api-1  | Traceback (most recent call last):
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
ellandi-api-1  |     response = get_response(request)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
ellandi-api-1  |     response = response.render()
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
ellandi-api-1  |     self.content = self.rendered_content
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
ellandi-api-1  |     ret = renderer.render(self.data, accepted_media_type, context)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
ellandi-api-1  |     ret = json.dumps(
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
ellandi-api-1  |     return json.dumps(*args, **kwargs)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
ellandi-api-1  |     return cls(
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
ellandi-api-1  |     chunks = self.iterencode(o, _one_shot=True)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
ellandi-api-1  |     return _iterencode(o, 0)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
ellandi-api-1  |     return super().default(obj)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
ellandi-api-1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
ellandi-api-1  | TypeError: Object of type Profession is not JSON serializable
ellandi-api-1  | [01/Aug/2022 11:01:39] "GET /me HTTP/1.1" 500 104307
ellandi-api-1  | [01/Aug/2022 11:01:40] "OPTIONS /me HTTP/1.1" 200 0
ellandi-api-1  | Internal Server Error: /me
ellandi-api-1  | Traceback (most recent call last):
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
ellandi-api-1  |     response = get_response(request)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
ellandi-api-1  |     response = response.render()
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
ellandi-api-1  |     self.content = self.rendered_content
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
ellandi-api-1  |     ret = renderer.render(self.data, accepted_media_type, context)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
ellandi-api-1  |     ret = json.dumps(
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
ellandi-api-1  |     return json.dumps(*args, **kwargs)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
ellandi-api-1  |     return cls(
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
ellandi-api-1  |     chunks = self.iterencode(o, _one_shot=True)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
ellandi-api-1  |     return _iterencode(o, 0)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
ellandi-api-1  |     return super().default(obj)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
ellandi-api-1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
ellandi-api-1  | TypeError: Object of type Profession is not JSON serializable
ellandi-api-1  | [01/Aug/2022 11:01:40] "GET /me HTTP/1.1" 500 104307
ellandi-api-1  | [01/Aug/2022 11:01:42] "OPTIONS /me HTTP/1.1" 200 0
ellandi-api-1  | Internal Server Error: /me
ellandi-api-1  | Traceback (most recent call last):
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
ellandi-api-1  |     response = get_response(request)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
ellandi-api-1  |     response = response.render()
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
ellandi-api-1  |     self.content = self.rendered_content
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
ellandi-api-1  |     ret = renderer.render(self.data, accepted_media_type, context)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
ellandi-api-1  |     ret = json.dumps(
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
ellandi-api-1  |     return json.dumps(*args, **kwargs)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
ellandi-api-1  |     return cls(
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
ellandi-api-1  |     chunks = self.iterencode(o, _one_shot=True)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
ellandi-api-1  |     return _iterencode(o, 0)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
ellandi-api-1  |     return super().default(obj)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
ellandi-api-1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
ellandi-api-1  | TypeError: Object of type Profession is not JSON serializable
ellandi-api-1  | [01/Aug/2022 11:01:42] "GET /me HTTP/1.1" 500 104307
ellandi-api-1  | [01/Aug/2022 11:01:46] "OPTIONS /me HTTP/1.1" 200 0
ellandi-api-1  | Internal Server Error: /me
ellandi-api-1  | Traceback (most recent call last):
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
ellandi-api-1  |     response = get_response(request)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
ellandi-api-1  |     response = response.render()
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
ellandi-api-1  |     self.content = self.rendered_content
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
ellandi-api-1  |     ret = renderer.render(self.data, accepted_media_type, context)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
ellandi-api-1  |     ret = json.dumps(
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
ellandi-api-1  |     return json.dumps(*args, **kwargs)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
ellandi-api-1  |     return cls(
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
ellandi-api-1  |     chunks = self.iterencode(o, _one_shot=True)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
ellandi-api-1  |     return _iterencode(o, 0)
ellandi-api-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
ellandi-api-1  |     return super().default(obj)
ellandi-api-1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
ellandi-api-1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
ellandi-api-1  | TypeError: Object of type Profession is not JSON serializable
ellandi-api-1  | [01/Aug/2022 11:01:46] "GET /me HTTP/1.1" 500 104307
```

**Comment by rottitime** [comment]
Steps

1. Add to Professions e.g.
```lang-js
//PATCH:  /users/b242e91a-c07f-4137-9513-117f17c465f1/
{
... 
professions: ["Social Research", "Statistical Service", "Tax"]
}
```
2. `/me` endpoint starts to throw errors:

**Endpoint**: 
/me
Authorization: Token 5b0abd1188580ce4a25c5e08443ecd343941415ac3eba0e62c303fca96813fa9

![Screenshot 2022-08-01 at 11 39 25](https://user-images.githubusercontent.com/1698584/182130869-093e7663-7772-4e3d-93f0-36052737fd9d.png)
