### ISSUE TITLE
Errors on 'develop' branch

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#473]
![Screenshot 2022-09-15 at 09 43 21](https://user-images.githubusercontent.com/1698584/190358293-76f8f45b-59e2-49fa-8b8e-7ad0dc0ad63f.png)

`make docker`

```
api_1               | Traceback (most recent call last):
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
api_1               |     self.connect()
api_1               |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 583, in connect
api_1               |     return real_connect(self)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
api_1               |     return func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
api_1               |     self.connection = self.get_new_connection(conn_params)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
api_1               |     return func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
api_1               |     connection = Database.connect(**conn_params)
api_1               |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
api_1               |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
api_1               | psycopg2.OperationalError: could not translate host name "ellandi-db" to address: Name or service not known
api_1               |
api_1               |
api_1               | The above exception was the direct cause of the following exception:
api_1               |
api_1               | Traceback (most recent call last):
api_1               |   File "manage.py", line 22, in <module>
api_1               |     main()
api_1               |   File "manage.py", line 18, in main
api_1               |     execute_from_command_line(sys.argv)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
api_1               |     utility.execute()
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
api_1               |     self.fetch_command(subcommand).run_from_argv(self.argv)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
api_1               |     self.execute(*args, **cmd_options)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
api_1               |     output = self.handle(*args, **options)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
api_1               |     res = handle_func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
api_1               |     self.check(databases=[database])
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
api_1               |     all_issues = checks.run_checks(
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
api_1               |     new_errors = check(app_configs=app_configs, databases=databases)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
api_1               |     errors.extend(model.check(**kwargs))
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1303, in check
api_1               |     *cls._check_indexes(databases),
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1695, in _check_indexes
api_1               |     connection.features.supports_covering_indexes or
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
api_1               |     res = instance.__dict__[self.name] = self.func(instance)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/features.py", line 92, in is_postgresql_11
api_1               |     return self.connection.pg_version >= 110000
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
api_1               |     res = instance.__dict__[self.name] = self.func(instance)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
api_1               |     with self.temporary_connection():
api_1               |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
api_1               |     return next(self.gen)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
api_1               |     with self.cursor() as cursor:
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
api_1               |     return func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
api_1               |     return self._cursor()
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
api_1               |     self.ensure_connection()
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
api_1               |     return func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
api_1               |     self.connect()
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
api_1               |     raise dj_exc_value.with_traceback(traceback) from exc_value
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
api_1               |     self.connect()
api_1               |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 583, in connect
api_1               |     return real_connect(self)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
api_1               |     return func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
api_1               |     self.connection = self.get_new_connection(conn_params)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
api_1               |     return func(*args, **kwargs)
api_1               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
api_1               |     connection = Database.connect(**conn_params)
api_1               |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
api_1               |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
api_1               | django.db.utils.OperationalError: could not translate host name "ellandi-db" to address: Name or service not known
api_1               |
organogram_1        | Traceback (most recent call last):
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
organogram_1        |     self.connect()
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
organogram_1        |     return func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
organogram_1        |     self.connection = self.get_new_connection(conn_params)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
organogram_1        |     return func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
organogram_1        |     connection = Database.connect(**conn_params)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
organogram_1        |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
organogram_1        | psycopg2.OperationalError: could not translate host name "organogram-db" to address: Name or service not known
organogram_1        |
organogram_1        |
organogram_1        | The above exception was the direct cause of the following exception:
organogram_1        |
organogram_1        | Traceback (most recent call last):
organogram_1        |   File "manage.py", line 22, in <module>
organogram_1        |     main()
organogram_1        |   File "manage.py", line 18, in main
organogram_1        |     execute_from_command_line(sys.argv)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
organogram_1        |     utility.execute()
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
organogram_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
organogram_1        |     self.execute(*args, **cmd_options)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
organogram_1        |     output = self.handle(*args, **options)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
organogram_1        |     res = handle_func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
organogram_1        |     self.check(databases=[database])
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
organogram_1        |     all_issues = checks.run_checks(
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
organogram_1        |     new_errors = check(app_configs=app_configs, databases=databases)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
organogram_1        |     errors.extend(model.check(**kwargs))
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1303, in check
organogram_1        |     *cls._check_indexes(databases),
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1695, in _check_indexes
organogram_1        |     connection.features.supports_covering_indexes or
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
organogram_1        |     res = instance.__dict__[self.name] = self.func(instance)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/features.py", line 92, in is_postgresql_11
organogram_1        |     return self.connection.pg_version >= 110000
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
organogram_1        |     res = instance.__dict__[self.name] = self.func(instance)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
organogram_1        |     with self.temporary_connection():
organogram_1        |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
organogram_1        |     return next(self.gen)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
organogram_1        |     with self.cursor() as cursor:
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
organogram_1        |     return func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
organogram_1        |     return self._cursor()
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
organogram_1        |     self.ensure_connection()
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
organogram_1        |     return func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
organogram_1        |     self.connect()
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
organogram_1        |     raise dj_exc_value.with_traceback(traceback) from exc_value
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
organogram_1        |     self.connect()
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
organogram_1        |     return func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
organogram_1        |     self.connection = self.get_new_connection(conn_params)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
organogram_1        |     return func(*args, **kwargs)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
organogram_1        |     connection = Database.connect(**conn_params)
organogram_1        |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
organogram_1        |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
organogram_1        | django.db.utils.OperationalError: could not translate host name "organogram-db" to address: Name or service not known
organogram_1        |
ellandi_api_1 exited with code 1
ellandi_organogram_1 exited with code 1
```

**Comment by rottitime** [comment]
Might be related to: https://github.com/i-dot-ai/ellandi/pull/472
