### ISSUE TITLE
Build prefech data fix

### ISSUE THREAD

**Issue by rottitime** [i-dot-ai/ellandi#559]
Data is not prefetched correctly on build. This means some data can not be preloaded for optimisation (Bug: https://trello.com/c/YVysv0hH/181-bug-b010-unable-to-add-skill-level)

https://github.com/i-dot-ai/ellandi/actions/runs/3173838036/jobs/5170941077#step:6:438
```
#16 54.67 Error: Sorry, there is a problem with the service. Try again later.
#16 54.67     at Object.fetchLanguages [as queryFn] (/app/web/.next/server/chunks/3384.js:74:11)
#16 54.67     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#16 54.77 Error: Sorry, there is a problem with the service. Try again later.
#16 54.77     at Object.fetchLanguageSkillLevels [as queryFn] (/app/web/.next/server/chunks/3384.js:80:11)
#16 54.77     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#16 54.88 Error: Sorry, there is a problem with the service. Try again later.
#16 54.88     at Object.fetchSkillLevels [as queryFn] (/app/web/.next/server/chunks/3384.js:95:11)
#16 54.88     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#16 54.98 Error: Sorry, there is a problem with the service. Try again later.
#16 54.98     at Object.fetchSkills [as queryFn] (/app/web/.next/server/chunks/3384.js:90:11)
#16 54.98     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#16 55.00 info  - Generating static pages (27/37)
#16 60.40 Route (pages)                              Size     First Load JS
```

**Comment by rickyp72** [comment]
Because of IP whitelisting the docker container build process doesn't currently have access to the `api` service to make pre-fetch calls

**Comment by rottitime** [comment]
Will look at a solution using the `web/prefetch` folder going forward
